name: build-and-deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: docker login -u "${{ secrets.DOCKER_USERNAME }}" -p "${{ secrets.DOCKER_PASSWORD }}"

      - name: Build Image for PHP
        run: |
          mv Dockerfile-php Dockerfile
          docker build -t strategic/hakathon-2024-php-app .

      - name: Publish Image for PHP to Docker Hub
        run: docker push strategic/hakathon-2024-php-app:latest

      - name: Build Image for Node
        run: |
          mv Dockerfile Dockerfile-php
          mv Dockerfile-node Dockerfile
          docker build -t strategic/hakathon-2024-node-app .

      - name: Publish Image for Node to Docker Hub
        run: docker push strategic/hakathon-2024-node-app:latest

  deploy:
    needs: build
    runs-on: aws-ec2
    steps:
      - name: Pull images from Docker Hub
        run: |
          docker pull strategic/hakathon-2024-php-app:latest
          docker pull strategic/hakathon-2024-node-app:latest

      - name: Delete Old Containers
        run: |
          docker rm -f php-app-container
          docker rm -f nodejs-app-container

      - name: Run Docker Containers
        run: |
          docker run -d -p 9000:8080 --name php-app-container strategic/hakathon-2024-php-app
          docker run -d -p 3000:8080 --name nodejs-app-container strategic/hakathon-2024-node-app
